"""Alembic environment: async engine, DSN from the application settings.

Purpose
    Run migrations against the same database the API talks to, using the same
    configuration object, so the two can never diverge.

Notes
    - There is no ORM metadata to autogenerate from. Migrations are written by
      hand as SQL, which for a schema with generated columns, GiST range indexes
      and pgvector opclasses is the honest choice: SQLAlchemy cannot express
      several of them, and a half-autogenerated migration is worse than none.
    - The DSN is rewritten to the postgresql+asyncpg dialect because SQLAlchemy
      needs the driver named; the application's asyncpg pool wants it absent.
"""

from __future__ import annotations

import asyncio
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# The API package lives one level up from this directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import get_settings

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_ASYNC_PREFIX = "postgresql+asyncpg://"


def _async_dsn() -> str:
    """The application DSN, in the dialect SQLAlchemy needs."""
    dsn = get_settings().dsn
    for prefix in ("postgresql://", "postgres://"):
        if dsn.startswith(prefix):
            return _ASYNC_PREFIX + dsn[len(prefix) :]
    return dsn


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it."""
    context.configure(
        url=_async_dsn(),
        target_metadata=None,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=None)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Apply migrations through a real connection."""
    config.set_main_option("sqlalchemy.url", _async_dsn())
    engine = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with engine.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
