/**
 * Dumps the current state of the Question Hub. Agents read this at the start of every task
 * so they build against the human's actual decisions rather than re-deriving them.
 *
 * `--json` OUTPUT IS FROZEN. It is the migration's old-reader equivalence oracle: the whole
 * §4.6 gate turns on `answers.mjs --json` being BYTE-IDENTICAL before and after the v1 -> v3
 * migration. It therefore projects exactly the fifteen pre-v3 fields, in a fixed order, from
 * the same IDENTITY_FIELDS list the migration is checked against — one definition, not two
 * that can drift. Never add a field to this projection.
 *
 * Usage:
 *   node tools/question-hub/answers.mjs                 # answered only, as Markdown
 *   node tools/question-hub/answers.mjs --all           # everything, with provisional defaults
 *   node tools/question-hub/answers.mjs --open          # unanswered only
 *   node tools/question-hub/answers.mjs --json          # machine-readable, frozen shape
 *   node tools/question-hub/answers.mjs --needs-review  # answers the platform could not reconcile
 *   node tools/question-hub/answers.mjs --file <path>   # read a DB file directly, no server
 */
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { IDENTITY_FIELDS } from './lib/migrate.mjs';

const HUB = process.env.HUB_URL ?? 'http://localhost:7777';
const argv = process.argv.slice(2);
const flags = new Set(argv);
const fileArg = argv[argv.indexOf('--file') + 1];

/** Withdrawn questions are excluded, which is what the pre-v3 server did by deleting them. */
function statsOf(questions) {
  const visible = questions.filter((q) => q.status !== 'withdrawn');
  return {
    total: visible.length,
    open: visible.filter((q) => q.status === 'open').length,
    answered: visible.filter((q) => q.status === 'answered').length,
    blockingOpen: visible.filter((q) => q.status === 'open' && q.blocking).length,
  };
}

async function load() {
  if (flags.has('--file')) {
    if (!fileArg) throw new Error('--file needs a path');
    const db = JSON.parse(await readFile(resolve(fileArg), 'utf8'));
    const questions = (db.questions ?? []).filter((q) => q.status !== 'withdrawn');
    return { questions, stats: statsOf(db.questions ?? []) };
  }
  const res = await fetch(HUB + '/api/questions', { cache: 'no-store' });
  if (!res.ok) throw new Error('HTTP ' + res.status);
  return res.json();
}

let data;
try {
  data = await load();
} catch (err) {
  console.error('[answers] cannot read the hub at ' + (flags.has('--file') ? fileArg : HUB) + ' — ' + err.message);
  if (!flags.has('--file')) console.error('[answers] start it with: node tools/question-hub/server.mjs');
  process.exit(1);
}

const wanted = flags.has('--all')
  ? data.questions
  : flags.has('--open')
    ? data.questions.filter((q) => q.status === 'open')
    : flags.has('--needs-review')
      ? data.questions.filter((q) => q.answerDetail?.needsReview)
      : data.questions.filter((q) => q.status === 'answered');

if (flags.has('--json')) {
  const questions = wanted.map((q) => Object.fromEntries(IDENTITY_FIELDS.map((field) => [field, q[field]])));
  console.log(JSON.stringify({ questions, stats: data.stats }, null, 2));
  process.exit(0);
}

const s = data.stats;
const lines = [
  '# Decisions — Question Hub state',
  '',
  '`' + s.answered + '/' + s.total + '` answered · `' + s.blockingOpen + '` blocking still open.',
  '',
  '> Generated by `tools/question-hub/answers.mjs`. Do not edit by hand.',
  '',
];

const bySection = new Map();
for (const q of wanted) {
  if (!bySection.has(q.section)) bySection.set(q.section, []);
  bySection.get(q.section).push(q);
}

for (const [section, questions] of bySection) {
  lines.push('## ' + section, '');
  for (const q of questions) {
    const mark = q.status === 'answered' ? '✅' : q.blocking ? '⛔' : '⬜';
    lines.push('### ' + mark + ' `' + q.id + '` ' + q.question);
    if (q.why) lines.push('', '_' + q.why + '_');
    lines.push('');
    if (q.status === 'answered') {
      lines.push('**Answer:** ' + q.answer);
      if (q.answerDetail?.source === 'accepted-recommendation') lines.push('', '_Accepted in bulk — the human endorsed the default but did not deliberate on it._');
      if (q.answerDetail?.needsReview) lines.push('', '**RE-CHECK** — this question was reworded after it was answered.');
    } else {
      lines.push('**Unanswered.** Provisional default: ' + (q.recommended ?? q.defaultAnswer ?? '_none — ask before relying on this_'));
    }
    if (q.note) lines.push('', '**Note:** ' + q.note);
    lines.push('');
  }
}

console.log(lines.join('\n'));
