/**
 * Geographic primitives shared by the spatial badges and the pre-computed passage record.
 *
 * Purpose
 *   Two features carry coordinates — the Route / 3D City badge sheets and the
 *   `spatial_data` block of a pre-computed passage (`docs/product/prd.md` §11). They
 *   must agree on axis order, so the type lives in one place instead of being restated.
 *
 * Axis order — the thing that goes wrong
 *   `[longitude, latitude]`, GeoJSON and Mapbox order. The PRD's worked example gives
 *   Troas as `[26.1553, 39.7428]`; Troas is 39.7 N, 26.2 E, so the first element is the
 *   longitude. Swapping them silently drops every pin in the wrong hemisphere, which is
 *   exactly the class of error CLAUDE.md forbids a model from producing — coordinates
 *   are resolved by code against a gazetteer, never emitted by a model.
 *
 * Dependencies
 *   None. Pure types.
 */

/** A point on the earth as `[longitude, latitude]` in decimal degrees, WGS 84. */
export type GeoCoordinates = readonly [longitude: number, latitude: number];

/** Where a map camera sits when a spatial sheet opens. */
export interface MapCamera {
  /** The point the camera looks at. */
  readonly center: GeoCoordinates;
  /** Mapbox zoom level; fractional values are meaningful and expected. */
  readonly zoomLevel: number;
}

/**
 * What part a place plays in the passage being read.
 *
 * `departure`, `island`, and `destination` are the values the PRD's worked example uses;
 * `waypoint` covers a place passed through that the example did not need to name.
 */
export type LocationRole = 'departure' | 'waypoint' | 'island' | 'destination';

/** A named place with coordinates, as rendered on the spatial sheet or the Discover map. */
export interface MappedLocation {
  /** The place name as scripture gives it, e.g. `Troas`. */
  readonly name: string;
  /** Where it is. Resolved by code against a gazetteer — never generated by a model. */
  readonly coordinates: GeoCoordinates;
  /** What part it plays in this passage. */
  readonly role: LocationRole;
  /** Whether a 3D reconstruction exists, which is what earns the place a `3d-city` badge. */
  readonly has3dReconstruction?: boolean;
}
