/**
 * The vendored coastline, and how it becomes two SVG paths.
 *
 * Purpose
 *   Decision `M-01`: a custom stylised map from GeoJSON, **no tile provider and no Mapbox
 *   token**. So the sea is a filled rectangle, the land is a filled path, and the lakes
 *   are subtracted from it. This module owns the one data file that makes that possible
 *   and the projection of it into path strings.
 *
 * The data
 *   `basemap.data.json` — Natural Earth 1:50m land and lakes, **public domain**, cropped
 *   to the biblical world and simplified. 100 land rings, 27 lake rings, 3,327 points,
 *   45,921 bytes. Generated by `tools/geo/build-basemap.mjs`; provenance and the licence
 *   text are in `data/raw/natural-earth/PROVENANCE.md`.
 *
 *   Public domain is why this file may be bundled at all. `Q-007` forbids redistributing
 *   the enrichment database because of share-alike licences; Natural Earth carries none,
 *   so the basemap ships with the client and the map works with no network at all.
 *
 * Two paths, not a hundred and twenty-seven
 *   Every ring is concatenated into one `d` string and drawn with `fill-rule: evenodd`.
 *   Holes inside a land polygon and lakes drawn over it both subtract themselves, and the
 *   whole basemap costs **two** DOM nodes instead of 127. That node count is the measured
 *   argument for `react-native-svg` over a canvas renderer; see `README.md` §2.
 *
 * Dependencies
 *   `./projection`, and the JSON. No React, no SVG library — the output is a string.
 */

import basemapData from './basemap.data.json';
import {
  project,
  visibleBounds,
  type GeoBounds,
  type MapTransform,
  type ScreenPoint,
  type Viewport,
} from './projection';

/** One closed ring, flattened to `[lon, lat, lon, lat, ...]` to keep the file small. */
export type FlatRing = readonly number[];

/** The vendored basemap, as the generator writes it. */
export interface Basemap {
  /** The line the sheet prints. Natural Earth asks for none; `AI-05` asks for one anyway. */
  readonly attribution: string;
  /** `public-domain`. Recorded so a licence audit never has to guess. */
  readonly license: string;
  /** Which Natural Earth layers this was cut from. */
  readonly source: string;
  /** The crop, as `[minLon, minLat, maxLon, maxLat]`. */
  readonly bounds: readonly number[];
  /** Simplification tolerance in degrees, so a reader of the file knows its resolution. */
  readonly tolerance: number;
  /** Land polygons and their holes. */
  readonly land: readonly FlatRing[];
  /** Lakes, subtracted from the land by the even-odd fill rule. */
  readonly lakes: readonly FlatRing[];
}

/** The vendored basemap. */
export const basemap: Basemap = basemapData;

/** Pixels of slack around the viewport before a ring is culled. */
const CULL_MARGIN = 8;

/**
 * Degrees of slack around the visible rectangle before a ring is culled geographically.
 *
 * Generous, because this cull runs before projection and its only job is to be cheap and
 * safe. A ring wrongly kept costs one projection pass; a ring wrongly dropped is a missing
 * coastline.
 */
const GEO_CULL_MARGIN = 1;

/** Consecutive points closer than this are the same pixel; emitting both is waste. */
const MIN_STEP = 0.6;

/** Decimal places kept in the emitted path. */
const PATH_PRECISION = 1;

/**
 * Each ring's geographic bounding box, computed once on first use.
 *
 * MEASURED: without this, every camera change projected all 3,327 points of all 127 rings
 * before discarding the ones off screen, and the browser showed a 40-67 ms task on every
 * sheet open and every rail resize — inside the 320 ms the sheet takes to slide up, which
 * is where a hitch is most visible. Comparing a ring's degrees against the visible degrees
 * first drops most of them for four floating-point comparisons each.
 */
const ringBoxes = new WeakMap<FlatRing, GeoBounds>();

/** The geographic bounding box of one flat ring, memoised. */
function boxOf(ring: FlatRing): GeoBounds {
  const cached = ringBoxes.get(ring);
  if (cached !== undefined) return cached;
  let minLon = Number.POSITIVE_INFINITY;
  let maxLon = Number.NEGATIVE_INFINITY;
  let minLat = Number.POSITIVE_INFINITY;
  let maxLat = Number.NEGATIVE_INFINITY;
  for (let index = 0; index + 1 < ring.length; index += 2) {
    const longitude = ring[index]!;
    const latitude = ring[index + 1]!;
    if (longitude < minLon) minLon = longitude;
    if (longitude > maxLon) maxLon = longitude;
    if (latitude < minLat) minLat = latitude;
    if (latitude > maxLat) maxLat = latitude;
  }
  const box: GeoBounds = { minLon, maxLon, minLat, maxLat };
  ringBoxes.set(ring, box);
  return box;
}

/**
 * True when a ring's degrees overlap the visible degrees, with a margin.
 *
 * Exported for `./coastline-extent`, which asks the same cheap question before paying for
 * a projection. Keeping one implementation keeps one cull margin.
 *
 * @param ring - One flat ring.
 * @param view - The visible degrees, from `visibleBounds`.
 * @returns True when the ring could touch the view. Side effects: none.
 */
export function ringOverlapsView(ring: FlatRing, view: GeoBounds): boolean {
  const box = boxOf(ring);
  return (
    box.maxLon >= view.minLon - GEO_CULL_MARGIN &&
    box.minLon <= view.maxLon + GEO_CULL_MARGIN &&
    box.maxLat >= view.minLat - GEO_CULL_MARGIN &&
    box.minLat <= view.maxLat + GEO_CULL_MARGIN
  );
}

/** Round for the path string, and never emit `-0`. */
function trim(value: number): number {
  return Number(value.toFixed(PATH_PRECISION)) + 0;
}

/** Project one flat ring, dropping points that land on the pixel just emitted. */
function projectRing(ring: FlatRing, transform: MapTransform): ScreenPoint[] {
  const points: ScreenPoint[] = [];
  for (let index = 0; index + 1 < ring.length; index += 2) {
    const next = project(transform, [ring[index]!, ring[index + 1]!]);
    const previous = points[points.length - 1];
    if (
      previous !== undefined &&
      Math.abs(next.x - previous.x) + Math.abs(next.y - previous.y) < MIN_STEP
    ) {
      continue;
    }
    points.push(next);
  }
  return points;
}

/** True when a projected ring has any chance of touching the viewport. */
function intersects(points: readonly ScreenPoint[], viewport: Viewport): boolean {
  let minX = Number.POSITIVE_INFINITY;
  let maxX = Number.NEGATIVE_INFINITY;
  let minY = Number.POSITIVE_INFINITY;
  let maxY = Number.NEGATIVE_INFINITY;
  for (const point of points) {
    minX = Math.min(minX, point.x);
    maxX = Math.max(maxX, point.x);
    minY = Math.min(minY, point.y);
    maxY = Math.max(maxY, point.y);
  }
  return (
    maxX >= -CULL_MARGIN &&
    minX <= viewport.width + CULL_MARGIN &&
    maxY >= -CULL_MARGIN &&
    minY <= viewport.height + CULL_MARGIN
  );
}

/** One ring as a closed SVG sub-path. */
function ringToSubPath(points: readonly ScreenPoint[]): string {
  const first = points[0];
  if (first === undefined) return '';
  let path = `M${trim(first.x)} ${trim(first.y)}`;
  for (let index = 1; index < points.length; index += 1) {
    path += `L${trim(points[index]!.x)} ${trim(points[index]!.y)}`;
  }
  return `${path}Z`;
}

/**
 * Project a set of rings into a single SVG path.
 *
 * @param rings - `basemap.land` or `basemap.lakes`.
 * @param transform - Where the map currently sits.
 * @param viewport - The pixel box, used to cull rings that cannot be seen.
 * @returns One `d` string containing every visible ring as a closed sub-path, to be drawn
 *   with `fillRule="evenodd"`. Empty when nothing is in view, which renders nothing rather
 *   than throwing. Side effects: none.
 */
export function ringsToPath(
  rings: readonly FlatRing[],
  transform: MapTransform,
  viewport: Viewport,
): string {
  const view = visibleBounds(transform, viewport);
  if (view === null) return '';
  let path = '';
  for (const ring of rings) {
    if (!ringOverlapsView(ring, view)) continue;
    const points = projectRing(ring, transform);
    if (points.length < 3 || !intersects(points, viewport)) continue;
    path += ringToSubPath(points);
  }
  return path;
}

/**
 * How many rings of a set are currently visible.
 *
 * Exposed for the component test that asserts culling actually culls: without it, a
 * regression that drew all 127 rings at every zoom would be invisible until a device
 * stuttered.
 *
 * @param rings - `basemap.land` or `basemap.lakes`.
 * @param transform - Where the map currently sits.
 * @param viewport - The pixel box.
 * @returns The count. Side effects: none.
 */
export function visibleRingCount(
  rings: readonly FlatRing[],
  transform: MapTransform,
  viewport: Viewport,
): number {
  const view = visibleBounds(transform, viewport);
  if (view === null) return 0;
  let count = 0;
  for (const ring of rings) {
    if (!ringOverlapsView(ring, view)) continue;
    const points = projectRing(ring, transform);
    if (points.length >= 3 && intersects(points, viewport)) count += 1;
  }
  return count;
}
